# Enable nice!view
CONFIG_ZMK_DISPLAY=n
# Disable idle blanking
CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=n

CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
